### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by zyze022145** [bertinetto/r2d2#1]
When I run the ‘scripts/train/experiments.sh’ command, I get a ‘no run_train.py’ or 'No module named 'fewshots'' problem. Is it wrong with me running the directory? Or is it a directory structure problem with the code?

**Comment by bertinetto** [comment]
Hi,
It's most likely that file/module missing from your python path.
Did you try to setup the conda environment as discussed in the readme?
Hope this helps,
Luca
