### ISSUE TITLE
Accuracy gaps on CIFAR-FS dataset

### ISSUE THREAD

**Issue by xhchrn** [bertinetto/r2d2#4]
Hi, thank you for sharing these well-written codes!

When I ran experiments with default setting on CIFAR-FS dataset, I notice quite large performance gaps compared to the results reported in the paper (near 4% for both 5-shot and 1-shot configurations). For the default setting, I mean the setting described in scripts/train/conf/fewshots.yaml

I checked the setting described in the paper I think it's consistent with the default setting in the repo. If the default setting is not the optimal, could you provide the optimal settings for the three datasets?

Best regards

**Comment by bertinetto** [comment]
Hi,
the experiments should be run as per https://github.com/bertinetto/r2d2/blob/master/scripts/train/experiments.sh , which contains the configuration as described in the paper.

Best,
Luca

**Comment by xhchrn** [comment]
Hi,
Thanks for pointing this out. And apologies that I totally missed the description in the README.

Best,
Xiaohan
