### ISSUE TITLE
probelm when running

### ISSUE THREAD

**Issue by Wongcheukwai** [bertinetto/r2d2#5]
Hi luca,
I set up the repo like that in readme.But when I goes to "Install the repo package: pip install -e .", my terminal says"-e option requires 1 argument". What does this mean?

**Comment by Wongcheukwai** [comment]
I just figured out I lost a dot after e. but after I installed e . ,the problem still existed. I just want to run one experiment so I used python ./scripts/train/run_train.py --log.exp_dir mini_r2d2 --data.dataset miniimagenet --data.way 16 --model.drop 0.1 --base_learner.init_adj_scale 1e-4 ,but it still says no modules fewshots. should I run it in fsrr env or my base env?

**Comment by bertinetto** [comment]
Hi,
Yeah, you should use the fsrr environment even if you only need a single
experiment.
Hope this helps.
Best,
Luca
